services:
  lina:
    build: .
    container_name: lina-container
    restart: always
    volumes:
      # BIND MOUNT: [Droplet Path] : [Container Path]
      - ./shared-lina-db-vol:/app/shared-lina-db-vol
    env_file:
      - ./lina.env

  caddy:
    image: caddy:latest
    container_name: caddy-container
    restart: always
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: