services:
  lina:
    image: ghcr.io/elethan/lina:latest
    build: .                          # used by: docker compose up --build
    container_name: lina-container
    restart: always
    volumes:
      - lina_data:/app/shared-lina-db-vol
    env_file:
      - ./lina.env

  caddy:
    image: caddy:latest
    container_name: caddy-container
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
lina_data:
  name: lina_data      
caddy_data:
caddy_config: